# 5.6_Discussion:_A_Comparison_of_the_Selection_and_Shrinkage_Methods
"""
Lecture: 5_Linear_Methods_for_Regression/5.6_Discussion:_A_Comparison_of_the_Selection_and_Shrinkage_Methods
Content: 5.6_Discussion:_A_Comparison_of_the_Selection_and_Shrinkage_Methods
"""
