# 10.4_Relationship_Between_the_Bootstrap_and_Bayesian_Inference
"""
Lecture: 10_Model_Inference_and_Averaging/10.4_Relationship_Between_the_Bootstrap_and_Bayesian_Inference
Content: 10.4_Relationship_Between_the_Bootstrap_and_Bayesian_Inference
"""
